name: Continuous Integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: unit tests
        run: make run-test

      - name: code coverage
        run: |
          pip3 install gcovr > /dev/null
          make coverage